name: 'Template Extractor'
description: 'Run templated extractor process'

on:
  workflow_call:
    inputs:
      name:
        description: 'name'
        type: string
        required: true
      path_python_file:
        description: 'path to the python function'
        type: string
        required: true
      workflow:
        description: 'workflow'
        type: string
        required: true

jobs:
  source_to_landing:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Caching requirements.txt
        uses: actions/cache@v3
        id: cache-req-requirements
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('requirements.txt') }}

      - name: Install requirements
        if: steps.cache-req-requirements.outputs.cache-hit != 'true'
        run: pip install -r requirements.txt

      - name: Run update data
        run: python -m ${{ inputs.path_python_file }}

      - name: Check for changes, Commit, and Push if needed
        run: |
          # Set up Git configuration
          git config --global user.name "adntayer"
          git config --global user.email "adntayer@users.noreply.github.com"
          changes=$(git ls-files --others --exclude-standard --modified -t)

          if [ -z "$changes" ]; then
            echo "No changes detected for ${{ inputs.workflow }} -->> ${{ inputs.name }}, skipping commit and push."
            exit 0
          else
            echo "Changes detected!"
            echo "$changes"
            echo "commiting..."
            git add .
            git commit -m "📡 [data ${{ inputs.workflow }} ${{ inputs.name }}]: automatic update data $(date)"
            echo "rebasing..."
            git pull origin main --rebase
            git push
          fi
