name: Check pre-commit

on:
  workflow_dispatch: null
  schedule:
    # (UTC TIME) -- At 08:30 on Sunday.
    - cron: '30 8 * * 0'

jobs:

  check_pre_commit:
    runs-on: ubuntu-latestw

    steps:
      - name: clone repo
        uses: actions/checkout@v2

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          activate-environment: true

      - name: setup python and libs # search version on file '.python-version'
        run: |
          uv python install
          uv pip install pre-commit

      - name: run pre-commit
        run: pre-commit run --all-files
