name: uv update

on:
  # Allows you to run this workflow manually from the Actions tab or through HTTP API
  workflow_dispatch:

  schedule:
    # (UTC TIME) -- At 10:00 on day-of-month 1.
    - cron: '0 10 1 * *'

jobs:

  pur:
    runs-on: ubuntu-latest

    steps:

      - name: checkout repo
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          activate-environment: true

      - name: setup python and libs # search version on file '.python-version'
        run: |
          uv python install
          uv sync

      - name: upgrade
        run: python -m upgrade

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: "build: uv update - automatic updated pip packages at ${{ steps.date.outputs.date }}"
          author: André Tayer <adntayer@users.noreply.github.com>
          committer: André Tayer <adntayer@users.noreply.github.com>
          signoff: false
          branch: pur
          delete-branch: true
          title: 'Update pip packages'
          draft: false